export interface AIModel {
  id: string;
  name: string;
  provider: string;
  description: string;
  plan: "free" | "pro";
  contextWindow: string;
  badge?: string;
  releaseDate?: string;
  tags?: string[];
}

export const MODELS: AIModel[] = [
  // ── March 2026 ───────────────────────────────────────────────────────────────
  {
    id: "nvidia/nemotron-3-super-120b-a12b:free",
    name: "Nemotron 3 Super 120B",
    provider: "NVIDIA",
    description:
      "NVIDIA 120B hybrid MoE model. Activates 12B params, 1M context, leads on AIME 2025 & SWE-Bench.",
    plan: "free",
    contextWindow: "262K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["reasoning", "coding", "agentic"],
  },
  {
    id: "nvidia/nemotron-3-nano-30b-a3b:free",
    name: "Nemotron 3 Nano 30B",
    provider: "NVIDIA",
    description:
      "Small MoE model by NVIDIA, 3B active params. High efficiency for agentic AI systems.",
    plan: "free",
    contextWindow: "256K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["fast", "agentic"],
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl:free",
    name: "Nemotron Nano 12B v2 VL",
    provider: "NVIDIA",
    description:
      "Improved Nemotron Nano 12B with Vision+Language capability and enhanced efficiency.",
    plan: "free",
    contextWindow: "256K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["vision", "reasoning", "fast"],
  },
  {
    id: "qwen/qwen3-coder:free",
    name: "Qwen3 Coder 480B",
    provider: "Alibaba",
    description:
      "State-of-the-art coding model, 480B MoE (35B active). Best free model for code generation.",
    plan: "free",
    contextWindow: "262K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["coding", "reasoning"],
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct:free",
    name: "Qwen3 Next 80B",
    provider: "Alibaba",
    description:
      "Instruction-tuned chat model in the Qwen3-Next series. Fast and stable.",
    plan: "free",
    contextWindow: "262K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["chat", "fast"],
  },
  {
    id: "openrouter/free",
    name: "Auto",
    provider: "OpenRouter",
    description:
      "Auto model routing mode for free users, selecting the best available backend model automatically.",
    plan: "free",
    contextWindow: "16K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["chat", "api", "free"],
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    description:
      "OpenAI's flagship multimodal model. Excellent at reasoning, coding, vision, and creative tasks.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2026-03",
    tags: ["multimodal", "reasoning", "coding"],
  },
  {
    id: "openai/o1",
    name: "o1",
    provider: "OpenAI",
    description:
      "OpenAI's reasoning model. Deep thinking for complex problem-solving, math, and code.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2025-12",
    tags: ["reasoning", "math", "coding"],
  },
  {
    id: "openai/o3-mini",
    name: "o3 Mini",
    provider: "OpenAI",
    description:
      "Compact reasoning model. Fast, cost-effective, strong at math and coding tasks.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2026-01",
    tags: ["reasoning", "fast", "coding"],
  },
  {
    id: "anthropic/claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    description:
      "Anthropic's latest Claude. Exceptional at coding, writing, analysis, and long-context tasks.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2026-03",
    tags: ["coding", "writing", "reasoning"],
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude Opus 4",
    provider: "Anthropic",
    description:
      "Anthropic's most capable model. Top-tier reasoning, coding, and complex task performance.",
    plan: "pro",
    contextWindow: "500K",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["reasoning", "coding", "writing"],
  },
  {
    id: "google/gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    description:
      "Google's fast and powerful Gemini model. 1M context, strong at multimodal & reasoning tasks.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2026-03",
    tags: ["fast", "multimodal", "long-context"],
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    description:
      "Google's advanced reasoning model. Excellent at complex analysis, coding, and creative tasks.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["reasoning", "coding", "multimodal"],
  },
  {
    id: "meta-llama/llama-3.3-405b-instruct:free",
    name: "Llama 3.3 405B",
    provider: "Meta",
    description:
      "Meta's largest open model. 405B parameters, top-tier performance across benchmarks.",
    plan: "free",
    contextWindow: "128K",
    badge: "Free",
    releaseDate: "2026-01",
    tags: ["general", "reasoning", "multilingual"],
  },
  {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    provider: "Mistral AI",
    description:
      "Mistral's flagship model. Top European AI, excellent at coding, reasoning, and multilingual tasks.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2025-12",
    tags: ["coding", "reasoning", "multilingual"],
  },
  {
    id: "cohere/command-r-plus",
    name: "Command R+",
    provider: "Cohere",
    description:
      "Cohere's enterprise-grade model. Strong at RAG, tool use, and production deployments.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2025-10",
    tags: ["rag", "tool-use", "enterprise"],
  },
  // ── February 2026 ────────────────────────────────────────────────────────────
  {
    id: "minimax/minimax-m2.5:free",
    name: "MiniMax M2.5",
    provider: "MiniMax",
    description:
      "SOTA model for real-world productivity. 80.2% on SWE-Bench, handles Office, coding, browsing.",
    plan: "free",
    contextWindow: "197K",
    badge: "Free",
    releaseDate: "2026-02",
    tags: ["coding", "agentic", "productivity"],
  },
  {
    id: "google/gemma-3-27b-it:free",
    name: "Gemma 3 27B",
    provider: "Google",
    description:
      "Google's open model. Strong reasoning, instruction following, and multilingual capabilities.",
    plan: "free",
    contextWindow: "131K",
    badge: "Free",
    releaseDate: "2026-02",
    tags: ["general", "multilingual"],
  },
  {
    id: "z-ai/glm-4.5-air:free",
    name: "GLM 4.5 Air",
    provider: "Z-AI",
    description:
      "GLM 4.5 Air is a lightweight open model optimized for fast multi-turn chat and reasoning.",
    plan: "free",
    contextWindow: "64K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["chat", "fast", "multilingual"],
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    description:
      "Fast & affordable GPT-4 class model. Great balance of speed, cost, and capability.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["fast", "affordable"],
  },
  {
    id: "anthropic/claude-3.5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    description:
      "Anthropic's fastest model. Near-instant responses with solid reasoning and coding ability.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["fast", "coding"],
  },
  {
    id: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    description:
      "Top open-source reasoning model. Rivals o1 on math, science & coding at a fraction of the cost.",
    plan: "pro",
    contextWindow: "164K",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["reasoning", "coding", "math"],
  },
  // ── January 2026 ─────────────────────────────────────────────────────────────
  {
    id: "stepfun/step-3.5-flash:free",
    name: "Step 3.5 Flash",
    provider: "StepFun",
    description:
      "StepFun's fastest open-source model. 196B MoE (11B active), reasoning-focused, speed-efficient.",
    plan: "free",
    contextWindow: "256K",
    badge: "Free",
    releaseDate: "2026-01",
    tags: ["reasoning", "fast"],
  },
  {
    id: "arcee-ai/trinity-large-preview:free",
    name: "Trinity Large Preview",
    provider: "Arcee AI",
    description:
      "400B MoE frontier model (13B active). Excellent at creative writing, roleplay, and agentic tasks.",
    plan: "free",
    contextWindow: "128K",
    badge: "Free",
    releaseDate: "2026-01",
    tags: ["creative", "roleplay", "agentic"],
  },
  {
    id: "arcee-ai/trinity-mini:free",
    name: "Trinity Mini",
    provider: "Arcee AI",
    description:
      "26B MoE (3B active), 128 experts. Strong function calling, long-context reasoning.",
    plan: "free",
    contextWindow: "131K",
    badge: "Free",
    releaseDate: "2026-01",
    tags: ["fast", "function-calling"],
  },
  // ── Older ─────────────────────────────────────────────────────────────────────
  {
    id: "meta-llama/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B",
    provider: "Meta",
    description:
      "Meta's best open model. Strong multilingual reasoning, dialogue, and instruction following.",
    plan: "free",
    contextWindow: "66K",
    badge: "Free",
    releaseDate: "2025-12",
    tags: ["general", "multilingual"],
  },

  {
    id: "google/gemma-3-12b-it:free",
    name: "Gemma 3 12B",
    provider: "Google",
    description:
      "Lightweight Google open model. Fast responses, good for everyday tasks.",
    plan: "free",
    contextWindow: "33K",
    badge: "Free",
    releaseDate: "2025-10",
    tags: ["fast", "lightweight"],
  },
  {
    id: "meta-llama/llama-3.2-3b-instruct:free",
    name: "Llama 3.2 3B",
    provider: "Meta",
    description:
      "Ultra-lightweight Llama model. Best for simple tasks where speed is priority.",
    plan: "free",
    contextWindow: "131K",
    badge: "Free",
    releaseDate: "2025-09",
    tags: ["fast", "lightweight"],
  },
  {
    id: "nousresearch/hermes-3-llama-3.1-405b:free",
    name: "Hermes 3 Llama 405B",
    provider: "Nous Research",
    description:
      "Massive 405B fine-tune of Llama 3.1. Exceptional reasoning, complex instruction following.",
    plan: "free",
    contextWindow: "131K",
    badge: "Free",
    releaseDate: "2025-08",
    tags: ["reasoning", "large"],
  },
  // ── Additional Pro Models ─────────────────────────────────────────────────────
  {
    id: "openai/gpt-oss-120b:free",
    name: "GPT-OSS 120B",
    provider: "OpenAI",
    description:
      "Open-source optimized GPT 120B model, free plan for standard chat and reasoning.",
    plan: "free",
    contextWindow: "128K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["free", "reasoning", "coding"],
  },
  {
    id: "openai/gpt-oss-20b:free",
    name: "GPT-OSS 20B",
    provider: "OpenAI",
    description:
      "Open-source optimized GPT 20B model, fast and lightweight for interactive applications.",
    plan: "free",
    contextWindow: "64K",
    badge: "Free",
    releaseDate: "2026-03",
    tags: ["free", "fast", "chat"],
  },
  {
    id: "openai/gpt-4.5",
    name: "GPT-4.5",
    provider: "OpenAI",
    description:
      "OpenAI's latest flagship model with improved reasoning and coding capabilities.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2025-12",
    tags: ["reasoning", "coding", "multimodal"],
  },
  {
    id: "openai/gpt-4.5-turbo",
    name: "GPT-4.5 Turbo",
    provider: "OpenAI",
    description:
      "Faster version of GPT-4.5 with same high quality, optimized for speed.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2026-02",
    tags: ["fast", "reasoning", "coding"],
  },
  {
    id: "openai/o1-pro",
    name: "o1 Pro",
    provider: "OpenAI",
    description:
      "Premium reasoning model with deeper thinking and longer context.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2026-01",
    tags: ["reasoning", "math", "coding"],
  },
  {
    id: "openai/o3",
    name: "o3",
    provider: "OpenAI",
    description:
      "Next-generation reasoning model with massive context and advanced problem-solving.",
    plan: "pro",
    contextWindow: "500K",
    badge: "Pro",
    releaseDate: "2026-03",
    tags: ["reasoning", "coding", "long-context"],
  },
  {
    id: "anthropic/claude-3-opus-20240229",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    description:
      "Anthropic's most powerful model for complex tasks and reasoning.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["reasoning", "coding", "writing"],
  },
  {
    id: "anthropic/claude-3-sonnet-20240229",
    name: "Claude 3 Sonnet",
    provider: "Anthropic",
    description: "Balanced Claude model with strong performance across tasks.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["coding", "writing", "reasoning"],
  },
  {
    id: "anthropic/claude-3-haiku-20240307",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    description: "Fast and cost-effective Claude model for quick responses.",
    plan: "pro",
    contextWindow: "200K",
    badge: "Pro",
    releaseDate: "2024-03",
    tags: ["fast", "coding"],
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    description:
      "Google's powerful model with 1M context and strong multimodal capabilities.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["multimodal", "long-context", "reasoning"],
  },
  {
    id: "google/gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "Google",
    description: "Fast and efficient Gemini model with 1M context.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["fast", "multimodal", "long-context"],
  },
  {
    id: "google/gemini-2.0-pro",
    name: "Gemini 2.0 Pro",
    provider: "Google",
    description: "Advanced Gemini model with enhanced reasoning and coding.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2025-12",
    tags: ["reasoning", "coding", "multimodal"],
  },
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    description:
      "Ultra-fast Gemini model with low latency and high throughput.",
    plan: "pro",
    contextWindow: "1M",
    badge: "Pro",
    releaseDate: "2026-01",
    tags: ["fast", "multimodal", "reasoning"],
  },
  {
    id: "meta-llama/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B",
    provider: "Meta",
    description: "Meta's 405B parameter model with top-tier performance.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-07",
    tags: ["general", "reasoning", "multilingual"],
  },
  {
    id: "meta-llama/llama-3.2-90b-instruct",
    name: "Llama 3.2 90B",
    provider: "Meta",
    description:
      "Large Llama model with strong instruction following and reasoning.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-09",
    tags: ["general", "reasoning"],
  },
  {
    id: "mistralai/mistral-large-2407",
    name: "Mistral Large 2407",
    provider: "Mistral AI",
    description: "Latest Mistral Large model with improved capabilities.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-07",
    tags: ["coding", "reasoning", "multilingual"],
  },
  {
    id: "mistralai/mistral-medium-2312",
    name: "Mistral Medium",
    provider: "Mistral AI",
    description: "Mid-sized Mistral model with excellent performance.",
    plan: "pro",
    contextWindow: "32K",
    badge: "Pro",
    releaseDate: "2023-12",
    tags: ["coding", "reasoning"],
  },
  {
    id: "mistralai/mistral-small-2312",
    name: "Mistral Small 2312",
    provider: "Mistral AI",
    description: "Compact Mistral model for fast and efficient tasks.",
    plan: "pro",
    contextWindow: "8K",
    badge: "Pro",
    releaseDate: "2023-12",
    tags: ["fast", "coding"],
  },
  {
    id: "microsoft/phi-4",
    name: "Phi-4",
    provider: "Microsoft",
    description:
      "Microsoft's advanced small language model with strong reasoning.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-03",
    tags: ["reasoning", "coding", "efficient"],
  },
  {
    id: "microsoft/phi-3.5-mini",
    name: "Phi-3.5 Mini",
    provider: "Microsoft",
    description: "Compact Phi model with excellent performance for its size.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-04",
    tags: ["fast", "reasoning"],
  },
  {
    id: "microsoft/phi-3.5-moe",
    name: "Phi-3.5 MoE",
    provider: "Microsoft",
    description: "Mixture of Experts version of Phi-3.5 for better quality.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-05",
    tags: ["reasoning", "coding"],
  },
  {
    id: "reka/reka-core",
    name: "Reka Core",
    provider: "Reka AI",
    description: "Reka's flagship multimodal model with vision and reasoning.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-03",
    tags: ["multimodal", "reasoning", "vision"],
  },
  {
    id: "xai/grok-2",
    name: "Grok-2",
    provider: "xAI",
    description: "xAI's advanced model with real-time knowledge and reasoning.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-08",
    tags: ["reasoning", "coding", "real-time"],
  },
  {
    id: "xai/grok-2-vision",
    name: "Grok-2 Vision",
    provider: "xAI",
    description: "Grok-2 with multimodal vision capabilities.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-08",
    tags: ["multimodal", "vision", "reasoning"],
  },
  {
    id: "baidu/ernie-4.5",
    name: "Ernie 4.5",
    provider: "Baidu",
    description:
      "Baidu's latest large language model with strong Chinese and English capabilities.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-10",
    tags: ["multilingual", "reasoning", "coding"],
  },
  {
    id: "baidu/ernie-4.0-turbo",
    name: "Ernie 4.0 Turbo",
    provider: "Baidu",
    description: "Fast version of Ernie 4.0 with optimized performance.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-06",
    tags: ["fast", "multilingual"],
  },
  {
    id: "tencent/hunyuan-standard",
    name: "Hunyuan Standard",
    provider: "Tencent",
    description:
      "Tencent's general-purpose large model with strong Chinese understanding.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-09",
    tags: ["multilingual", "reasoning"],
  },
  {
    id: "tencent/hunyuan-large",
    name: "Hunyuan Large",
    provider: "Tencent",
    description: "Tencent's largest model with top-tier performance.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-10",
    tags: ["reasoning", "coding", "multilingual"],
  },
  {
    id: "alibaba/qwen-max",
    name: "Qwen Max",
    provider: "Alibaba",
    description: "Alibaba's most powerful Qwen model with advanced reasoning.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-05",
    tags: ["reasoning", "coding", "multilingual"],
  },
  {
    id: "alibaba/qwen-plus",
    name: "Qwen Plus",
    provider: "Alibaba",
    description: "Balanced Qwen model with strong performance across tasks.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-04",
    tags: ["coding", "reasoning"],
  },
  {
    id: "alibaba/qwen-turbo",
    name: "Qwen Turbo",
    provider: "Alibaba",
    description: "Fast and efficient Qwen model for quick responses.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-03",
    tags: ["fast", "coding"],
  },
  {
    id: "deepseek/deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    description:
      "DeepSeek's latest flagship model with superior reasoning and coding.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-12",
    tags: ["reasoning", "coding", "math"],
  },
  {
    id: "deepseek/deepseek-v2.5",
    name: "DeepSeek V2.5",
    provider: "DeepSeek",
    description: "Improved version of DeepSeek V2 with better performance.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-09",
    tags: ["reasoning", "coding"],
  },
  {
    id: "databricks/dbrx",
    name: "DBRX",
    provider: "Databricks",
    description:
      "Databricks' state-of-the-art open model with 132B parameters.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-03",
    tags: ["general", "reasoning", "coding"],
  },
  {
    id: "mosaicml/mpt-30b",
    name: "MPT-30B",
    provider: "MosaicML",
    description:
      "MosaicML's 30B parameter model with strong instruction following.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2023-08",
    tags: ["general", "instruction-following"],
  },
  {
    id: "togethercomputer/llama-2-70b-chat",
    name: "Llama 2 70B Chat",
    provider: "Together Computer",
    description: "Together's fine-tuned Llama 2 70B for chat.",
    plan: "pro",
    contextWindow: "4096",
    badge: "Pro",
    releaseDate: "2023-07",
    tags: ["chat", "general"],
  },
  {
    id: "perplexity/llama-3.1-sonar-small-128k",
    name: "Perplexity Sonar Small",
    provider: "Perplexity",
    description:
      "Perplexity's search-augmented model for real-time information.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["search", "real-time", "reasoning"],
  },
  {
    id: "perplexity/llama-3.1-sonar-large-128k",
    name: "Perplexity Sonar Large",
    provider: "Perplexity",
    description:
      "Perplexity's large search-augmented model with comprehensive answers.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-02",
    tags: ["search", "real-time", "reasoning"],
  },
  {
    id: "fireworks/firefunction-v2",
    name: "FireFunction V2",
    provider: "Fireworks AI",
    description: "Fireworks' function-calling model optimized for tool use.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-04",
    tags: ["function-calling", "tool-use"],
  },
  {
    id: "fireworks/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B Instruct",
    provider: "Fireworks AI",
    description: "Fireworks' hosted Llama 3.1 405B with high performance.",
    plan: "pro",
    contextWindow: "128K",
    badge: "Pro",
    releaseDate: "2024-07",
    tags: ["general", "reasoning", "multilingual"],
  },
];

export const DEFAULT_FREE_MODEL = "openrouter/free";
export const DEFAULT_PRO_MODEL = "openai/gpt-4o-mini";

export function getDefaultModel(plan: "free" | "pro"): string {
  return plan === "pro" ? DEFAULT_PRO_MODEL : DEFAULT_FREE_MODEL;
}

export function canUseModel(
  modelId: string,
  userPlan: "free" | "pro",
): boolean {
  const model = MODELS.find((m) => m.id === modelId);
  if (!model) return false;
  if (userPlan === "pro") return true;
  return model.plan === "free";
}
